#include "Models/DynamicPixelsException.h"

const TMap<FString, EErrorCode> FErrorMapper::ErrorMap = {
	{"invalid token", EErrorCode::InvalidToken},
	{"user already exist", EErrorCode::UserAlreadyExist},
	{"user notfound", EErrorCode::UserNotFound},
	{"invalid_access_token", EErrorCode::InvalidAccessToken},
	{"payload is not valid", EErrorCode::PayloadNotValid},
	{"cant find user_id from token", EErrorCode::UserIdNotFoundFromToken},
	{"target user is not valid", EErrorCode::TargetUserNotValid},
	{"cant request to yourself", EErrorCode::CannotRequestYourself},
	{"request already exist", EErrorCode::RequestAlreadyExist},
	{"request notfound", EErrorCode::RequestNotFound},
	{"friendship notfound", EErrorCode::FriendshipNotFound},
	{"leaderboard's participants is not user", EErrorCode::LeaderboardParticipantsNotUser},
	{"leaderboard notfound", EErrorCode::LeaderboardNotFound},
	{"leaderboard's participants is not party", EErrorCode::LeaderboardParticipantsNotParty},
	{"party notfound", EErrorCode::PartyNotFound},
	{"team is not valid", EErrorCode::InvalidTeam},
	{"channels is not valid", EErrorCode::InvalidChannels},
	{"membership is already exist", EErrorCode::MembershipAlreadyExist},
	{"permission denied", EErrorCode::PermissionDenied},
	{"membership notfound", EErrorCode::MembershipNotFound},
	{"row notfound", EErrorCode::RowNotFound},
	{"sort should be asc or desc", EErrorCode::InvalidSortOrder},
	{"email already exist", EErrorCode::EmailAlreadyExist},
	{"phone_number already exist", EErrorCode::PhoneNumberAlreadyExist},
	{"username already exist", EErrorCode::UsernameAlreadyExist},
	{"invalid response", EErrorCode::InvalidResponse},
	{"achievement notfound", EErrorCode::AchievementNotFound},
	{"ConnectionNotReady", EErrorCode::ConnectionNotReady},
	{"SdkAlreadyInitialized", EErrorCode::SdkAlreadyInitialized},
};
